# Generated by Django 5.1.6 on 2025-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('categorie', models.CharField(choices=[('anniversaire', 'Anniversaire'), ('mariage', 'Mariage'), ('bapteme', 'Baptême'), ('communion', 'Communion'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_realisation', models.DateField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Photo de galerie',
                'verbose_name_plural': 'Photos de galerie',
                'ordering': ['-ordre_affichage', '-date_realisation'],
            },
        ),
    ]
