# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_galeriephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleevenement',
            name='contenu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleevenement',
            name='date_evenement',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleevenement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='articleevenement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articleevenement',
            name='date_publication',
        ),
    ]

