# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_fix_articleevenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleevenement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]

