# Generated by Django 5.1.6 on 2025-10-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_add_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='qr_code_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='qr_code_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articleevenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='articleevenement',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='galeriephoto',
            name='categorie',
            field=models.CharField(choices=[('gateaux', 'Gâteaux'), ('evenements', 'Événements'), ('ateliers', 'Ateliers'), ('autres', 'Autres')], default='gateaux', max_length=20),
        ),
        migrations.AlterField(
            model_name='gateau',
            name='type',
            field=models.CharField(choices=[('anniversaire', 'Anniversaire'), ('mariage', 'Mariage'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
