# Generated by Django 5.1.6 on 2025-10-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_add_qr_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreslivraison',
            name='numero_patron',
            field=models.CharField(default='2250123456789', help_text='Numéro de téléphone du patron pour les dépôts', max_length=20),
        ),
    ]
