services:
  # Service Backend Django
  - type: web
    name: patisserie-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python setup_data.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: patisserie_project.settings_render
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  # Service Frontend React
  - type: web
    name: patisserie-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://patisserie-backend.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://patisserie-backend.onrender.com

