# Generated by Django 5.1.6 on 2025-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleevenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='gateau',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gateaux/'),
        ),
        migrations.AlterField(
            model_name='gateau',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parametreslivraison',
            name='prix_livraison',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
