# Generated by Django 5.1.6 on 2025-07-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_alter_articleevenement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_whatsapp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='whatsapp_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
